# -*- coding: utf-8 -*-
"""01_Tools_and_Technique_by_70189383_(AYESHA_NAFIS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-4pm8LT_cYrup1nzfs_UAdF55b-yQi7
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ayeshanafees48/Tools-and-Tech-70189383
# %cd Tools-and-Tech-70189383

!ls

import warnings
warnings.filterwarnings("ignore")

"""## **PREPROCESSING**"""

#Imports
from Encoder import Encoder
import pandas as pd
from Scalar import Scaler
import numpy as np
import warnings
# Load Dataset
df = pd.read_csv("CA1.csv")
print("---------------------------------------------")
print("Original Dataset Shape:", df.shape)
print("---------------------------------------------")

"""# **DATA CLEANING**

# **Checking Missing Values**
"""

# Check missing values
print("Missing Values in Each Column:")
print(df.isnull().sum())
# Percentage of missing values
print("\nMissing Values Percentage:")
print((df.isnull().sum() / len(df)) * 100)

"""# **Checking Duplicates**"""

duplicate_Count = df.duplicated().sum()
print("Duplicate Count (before):", duplicate_Count)
if duplicate_Count > 0:
    duplicate_Rows = df[df.duplicated(keep=False)]
    print("\nDuplicate Rows are:")
    print(duplicate_Rows)
    df = df.drop_duplicates()
    new_count = df.duplicated().sum()
    print("\nDuplicates removed successfully!")
    print("Duplicate Count (after):", new_count)
    print("New shape of dataset:", df.shape)
else:
    print("\nThere is no duplicate in dataset (even after cleaning)")

"""# **Checking Typo and Spelling Errors**"""

valid_months = ['jan','feb','mar','apr','may','june','jul','aug','sep','oct','nov','dec']
df['Month'] = df['Month'].str.lower().str.strip()
invalid_months = df[~df['Month'].isin(valid_months)]['Month'].unique()
print("Invalid Month Values:", invalid_months)
valid_types = ['returning_visitor', 'new_visitor', 'other']
df['VisitorType'] = df['VisitorType'].str.lower().str.strip()
invalid_types = df[~df['VisitorType'].isin(valid_types)]['VisitorType'].unique()
print("Invalid VisitorType Values:", invalid_types)

"""# **Handling Outliers**"""

import numpy as np
numerical_cols = [
"Administrative",
"Administrative_Duration",
"Informational",
"Informational_Duration",
"ProductRelated",
"ProductRelated_Duration",
"BounceRates",
"ExitRates",
"PageValues",
"SpecialDay"
]
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers:", len(outliers))
import matplotlib.pyplot as plt
import seaborn as sns
print("\nOutlier Type Detection")
for col in numerical_cols:
    skew_val = df[col].skew()
    if skew_val > 0.5:
        skew_type = "Right Skewed (Positive Skew)"
    elif skew_val < -0.5:
        skew_type = "Left Skewed (Negative Skew)"
    else:
        skew_type = "Approximately Symmetric"
    print(f"{col} --> Skewness: {skew_val:.2f} --> {skew_type}")
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f"{col} ({skew_type})")
    plt.show()

"""**As the outliers are Right Skewed so there is a need to apply Log Transformation**"""

transform_Columns = ["Administrative" , "Informational_Duration" , "Informational" , "ProductRelated" , "ProductRelated_Duration" , "BounceRates" , "ExitRates" , "PageValues" , "SpecialDay"]
for transformation in transform_Columns:
  df[transformation] = np.log1p(df[transformation])
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers After Log Transformation:", len(outliers))

"""# **Apply Capping to reach to the zero**"""

numeric_Columns = ["Administrative_Duration", "Informational" , "Informational_Duration" , "ProductRelated" , "ProductRelated_Duration" , "BounceRates" , "ExitRates" , "PageValues" , "SpecialDay"]
for int_column in numeric_Columns:
  qunatile_1 = df[int_column].quantile(0.25)
  quantile_3 = df[int_column].quantile(0.75)
  calculated_IQR = quantile_3 - qunatile_1
  lower_Bound = qunatile_1 - (1.5 * calculated_IQR)
  upper_Bound = quantile_3 + (1.5 * calculated_IQR)
  df[int_column] = np.where(df[int_column] < lower_Bound , lower_Bound , df[int_column])
  df[int_column] = np.where(df[int_column] > upper_Bound , upper_Bound , df[int_column])
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers After Capping:", len(outliers))

"""# **FEATURE ENGINNERING & DATA TRANSFORMATION**"""

# 1. Total Time Spent
df['Total_Time'] = ( df['Administrative_Duration'] + df['Informational_Duration'] + df['ProductRelated_Duration'] )
# 2. Total Pages Visited
df['Total_Pages'] = ( df['Administrative'] + df['Informational'] + df['ProductRelated'] )
# 3. Engagement Ratio
df['Engagement_Ratio'] = df['Total_Time'] / (df['Total_Pages'] + 1)
# 4. Value Per Page
df['Value_Per_Page'] = df['PageValues'] / (df['ProductRelated'] + 1)
print("\nNew Features Added Successfully")
print(df[['Total_Time', 'Total_Pages', 'Engagement_Ratio', 'Value_Per_Page']].head())
df.info()

"""# **ADVANCE FEATURE ENGINNERING & INTERACTION**


*   Polynomial Features



"""

from sklearn.preprocessing import PolynomialFeatures
poly_cols = [
    'Total_Time',
    'Total_Pages',
    'Engagement_Ratio',
    'Value_Per_Page'
]
# Polynomial Feature Object
poly = PolynomialFeatures(degree=2, include_bias=False)
# Create Features
poly_features = poly.fit_transform(df[poly_cols])
# Feature Names
poly_feature_names = poly.get_feature_names_out(poly_cols)
# Convert to DataFrame
poly_df = pd.DataFrame(poly_features, columns=poly_feature_names)
# Remove original duplicate columns
poly_df = poly_df.drop(columns=poly_cols)
# Merge with original dataset
df = pd.concat([df.reset_index(drop=True), poly_df.reset_index(drop=True)], axis=1)
print("\nPolynomial Features Added Successfully")
df.info()

"""# **BINNING**"""

print(df['ProductRelated_Duration'].min())
print(df['ProductRelated_Duration'].max())
print(df['PageValues'].min())
print(df['PageValues'].max())

# ProductRelated_Duration
df['ProductRelated_Duration_Bin'] = pd.cut(
    df['ProductRelated_Duration'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)
# BounceRates
df['BounceRates_Bin'] = pd.cut(
    df['BounceRates'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)

print(df[['ProductRelated_Duration_Bin',
          'BounceRates_Bin']].head())

"""# **Feature Transformation: Scaling and Encoding**"""

from Encoder import Encoder
from Scalar import Scaler
import numpy as np
import warnings
# -------------------------------
# Encoding
# -------------------------------
binary_cols = ["Weekend" , "Revenue"]
nominal_cols = ["Month", "VisitorType"]
ordinal_cols = ["Browser" , "Region" , "OperatingSystems" , "TrafficType" , 'ProductRelated_Duration_Bin', 'BounceRates_Bin']
encoder = Encoder()
# Apply encoding on full dataset
X = encoder.label_encode(df, binary_cols)
X = encoder.onehot_encode(df, nominal_cols)
X = encoder.label_encode(df, ordinal_cols)
print("---------------------------------------------")
print("After Encoding Shape:", X.shape)
print("---------------------------------------------")
# -------------------------------
# Scaling
# -------------------------------
numerical_cols = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
    "Total_Time",
    "Total_Pages",
    "Engagement_Ratio",
    "Value_Per_Page"
]
scaler = Scaler(method="standard")
# Fit + Transform on full dataset
X = scaler.fit_transform(df, numerical_cols)
X.describe()
print("---------------------------------------------")
print("After Scaling Shape:", df.shape)
print("---------------------------------------------")
X.head()

X.info()

"""# **STATISTICAL ANALYSIS**

"""

# -------------------------------
# Statistical Analysis
# -------------------------------
numerical_cols = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay"
]
# Mean
print("Mean:")
print(df[numerical_cols].mean())
# Median
print("\nMedian:")
print(df[numerical_cols].median())
# Mode
print("\nMode:")
print(df[numerical_cols].mode().iloc[0])
# Standard Deviation
print("\nStandard Deviation:")
print(df[numerical_cols].std())
# Variance
print("\nVariance:")
print(df[numerical_cols].var())
# Minimum Values
print("\nMinimum Values:")
print(df[numerical_cols].min())
# Maximum Values
print("\nMaximum Values:")
print(df[numerical_cols].max())
# Complete Statistical Summary
print("\nStatistical Summary:")
print(df[numerical_cols].describe())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()