# -*- coding: utf-8 -*-
"""Copy of 01_Tools_and_Technique_by_70189383_(AYESHA_NAFIS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gil9EYlCrq_1X95cA0iqv1-7H5xOUBYx
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ayeshanafees48/Tools-and-Tech-70189383
# %cd Tools-and-Tech-70189383

!ls

import warnings
warnings.filterwarnings("ignore")

"""## **PREPROCESSING**"""

#Imports
from Encoder import Encoder
from Balancing_Data import Balancing_Data
from Cross_Validation import CrossValidation
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
from Scalar import Scaler
import numpy as np
import warnings
# Load Dataset
df = pd.read_csv("CA1.csv")
print("---------------------------------------------")
print("Original Dataset Shape:", df.shape)
print("---------------------------------------------")

"""# **Check Frequency of the data weather it is Balance or not**"""

print(df['Revenue'].value_counts())
print(df['Revenue'].value_counts(normalize=True) * 100)
import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(x=df['Revenue'])
plt.title("Revenue Distribution")
plt.show()

"""# **Dataset is imbalance so I apply SMOTE to the dataset to make sure the results are not biased.**

# **DATA CLEANING**

# **Checking Missing Values**
"""

# Check missing values
print("Missing Values in Each Column:")
print(df.isnull().sum())
# Percentage of missing values
print("\nMissing Values Percentage:")
print((df.isnull().sum() / len(df)) * 100)

"""# **Checking Duplicates**"""

duplicate_Count = df.duplicated().sum()
print("Duplicate Count (before):", duplicate_Count)
if duplicate_Count > 0:
    duplicate_Rows = df[df.duplicated(keep=False)]
    print("\nDuplicate Rows are:")
    print(duplicate_Rows)
    df = df.drop_duplicates()
    new_count = df.duplicated().sum()
    print("\nDuplicates removed successfully!")
    print("Duplicate Count (after):", new_count)
    print("New shape of dataset:", df.shape)
else:
    print("\nThere is no duplicate in dataset (even after cleaning)")

"""# **Checking Typo and Spelling Errors**"""

valid_months = ['jan','feb','mar','apr','may','june','jul','aug','sep','oct','nov','dec']
df['Month'] = df['Month'].str.lower().str.strip()
invalid_months = df[~df['Month'].isin(valid_months)]['Month'].unique()
print("Invalid Month Values:", invalid_months)
valid_types = ['returning_visitor', 'new_visitor', 'other']
df['VisitorType'] = df['VisitorType'].str.lower().str.strip()
invalid_types = df[~df['VisitorType'].isin(valid_types)]['VisitorType'].unique()
print("Invalid VisitorType Values:", invalid_types)

"""# **Handling Outliers**"""

import numpy as np
numerical_cols = [
"Administrative",
"Administrative_Duration",
"Informational",
"Informational_Duration",
"ProductRelated",
"ProductRelated_Duration",
"BounceRates",
"ExitRates",
"PageValues",
"SpecialDay"
]
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers:", len(outliers))
import matplotlib.pyplot as plt
import seaborn as sns
print("\nOutlier Type Detection")
for col in numerical_cols:
    skew_val = df[col].skew()
    if skew_val > 0.5:
        skew_type = "Right Skewed (Positive Skew)"
    elif skew_val < -0.5:
        skew_type = "Left Skewed (Negative Skew)"
    else:
        skew_type = "Approximately Symmetric"
    print(f"{col} --> Skewness: {skew_val:.2f} --> {skew_type}")
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f"{col} ({skew_type})")
    plt.show()

"""**As the outliers are Right Skewed so there is a need to apply Log Transformation**"""

transform_Columns = ["Administrative" , "Informational_Duration" , "Informational" , "ProductRelated" , "ProductRelated_Duration" , "BounceRates" , "ExitRates" , "PageValues" , "SpecialDay"]
for transformation in transform_Columns:
  df[transformation] = np.log1p(df[transformation])
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers After Log Transformation:", len(outliers))

"""# **Apply Capping to reach to the zero**"""

numeric_Columns = ["Administrative_Duration", "Informational" , "Informational_Duration" , "ProductRelated" , "ProductRelated_Duration" , "BounceRates" , "ExitRates" , "PageValues" , "SpecialDay"]
for int_column in numeric_Columns:
  qunatile_1 = df[int_column].quantile(0.25)
  quantile_3 = df[int_column].quantile(0.75)
  calculated_IQR = quantile_3 - qunatile_1
  lower_Bound = qunatile_1 - (1.5 * calculated_IQR)
  upper_Bound = quantile_3 + (1.5 * calculated_IQR)
  df[int_column] = np.where(df[int_column] < lower_Bound , lower_Bound , df[int_column])
  df[int_column] = np.where(df[int_column] > upper_Bound , upper_Bound , df[int_column])
for col in numerical_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print(col, "Outliers After Capping:", len(outliers))

"""# **FEATURE ENGINNERING & DATA TRANSFORMATION**"""

# 1. Total Time Spent
df['Total_Time'] = ( df['Administrative_Duration'] + df['Informational_Duration'] + df['ProductRelated_Duration'] )
# 2. Total Pages Visited
df['Total_Pages'] = ( df['Administrative'] + df['Informational'] + df['ProductRelated'] )
# 3. Engagement Ratio
df['Engagement_Ratio'] = df['Total_Time'] / (df['Total_Pages'] + 1)
# 4. Value Per Page
df['Value_Per_Page'] = df['PageValues'] / (df['ProductRelated'] + 1)
print("\nNew Features Added Successfully")
print(df[['Total_Time', 'Total_Pages', 'Engagement_Ratio', 'Value_Per_Page']].head())
df.info()

"""# **ADVANCE FEATURE ENGINNERING & INTERACTION**


*   Polynomial Features



"""

from sklearn.preprocessing import PolynomialFeatures
poly_cols = [
    'Total_Time',
    'Total_Pages',
    'Engagement_Ratio',
    'Value_Per_Page'
]
# Polynomial Feature Object
poly = PolynomialFeatures(degree=2, include_bias=False)
# Create Features
poly_features = poly.fit_transform(df[poly_cols])
# Feature Names
poly_feature_names = poly.get_feature_names_out(poly_cols)
# Convert to DataFrame
poly_df = pd.DataFrame(poly_features, columns=poly_feature_names)
# Remove original duplicate columns
poly_df = poly_df.drop(columns=poly_cols)
# Merge with original dataset
df = pd.concat([df.reset_index(drop=True), poly_df.reset_index(drop=True)], axis=1)
print("\nPolynomial Features Added Successfully")
df.info()

"""# **BINNING**"""

print(df['ProductRelated_Duration'].min())
print(df['ProductRelated_Duration'].max())
print(df['PageValues'].min())
print(df['PageValues'].max())

# ProductRelated_Duration
df['ProductRelated_Duration_Bin'] = pd.cut(
    df['ProductRelated_Duration'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)
# BounceRates
df['BounceRates_Bin'] = pd.cut(
    df['BounceRates'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)

print(df[['ProductRelated_Duration_Bin',
          'BounceRates_Bin']].head())

"""# **Feature Transformation: Scaling and Encoding**"""

binary_cols = ["Weekend" , "Revenue"]
nominal_cols = ["Month", "VisitorType"]
ordinal_cols = ["Browser" , "Region" , "OperatingSystems" , "TrafficType" , 'ProductRelated_Duration_Bin', 'BounceRates_Bin']
encoder = Encoder()
# Apply encoding on full dataset
X = encoder.label_encode(df, binary_cols)
X = encoder.onehot_encode(X, nominal_cols)
X = encoder.label_encode(X, ordinal_cols)
print("---------------------------------------------")
print("After Encoding Shape:", X.shape)
print("---------------------------------------------")
# -------------------------------
# Scaling
# -------------------------------
numerical_cols = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay",
    "Total_Time",
    "Total_Pages",
    "Engagement_Ratio",
    "Value_Per_Page"
]
scaler = Scaler(method="standard")
# Fit + Transform on full dataset
X = scaler.fit_transform(X, numerical_cols)
X.describe()
print("---------------------------------------------")
print("After Scaling Shape:", X.shape)
print("---------------------------------------------")
X.head()

X.info()

"""# **STATISTICAL ANALYSIS**

"""

# -------------------------------
# Statistical Analysis
# -------------------------------
numerical_cols = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay"
]
# Mean
print("Mean:")
print(df[numerical_cols].mean())
# Median
print("\nMedian:")
print(df[numerical_cols].median())
# Mode
print("\nMode:")
print(df[numerical_cols].mode().iloc[0])
# Standard Deviation
print("\nStandard Deviation:")
print(df[numerical_cols].std())
# Variance
print("\nVariance:")
print(df[numerical_cols].var())
# Minimum Values
print("\nMinimum Values:")
print(df[numerical_cols].min())
# Maximum Values
print("\nMaximum Values:")
print(df[numerical_cols].max())
# Complete Statistical Summary
print("\nStatistical Summary:")
print(df[numerical_cols].describe())

"""# **HEAT MAP**

"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

df[numerical_cols].hist(figsize=(15,10))
plt.tight_layout()
plt.show()

sns.countplot(x='VisitorType',hue='Revenue',data=df)
plt.title("Visitor Type vs Revenue")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x='Month',hue='Revenue',data=df)
plt.show()

"""# **FEATURE SELECION, VARIAN THRESHOLD, CORELATION FILTER, UNIVARIATE FEATURE SELECTION, SMOTE, MODEELLING, & EVALUATIONS**"""

# FEATURE SELECTION
# Target
y = X['Revenue']
X = X.drop(columns=['Revenue'])
print("Original Shape :", X.shape)
# VARIANCE THRESHOLD
vt = VarianceThreshold(threshold=0.01)
X_vt = vt.fit_transform(X)
selected_cols = X.columns[vt.get_support()]
X = pd.DataFrame(X_vt, columns=selected_cols)
print("After Variance Threshold :", X.shape)
# CORRELATION FILTER
corr_matrix = X.corr().abs()
upper_triangle = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
drop_cols = [col
    for col in upper_triangle.columns
    if any(upper_triangle[col] > 0.90)
]
X = X.drop(columns=drop_cols)
print("After Correlation Filter :", X.shape)
# TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42, stratify=y )
print("Train :", X_train.shape)
print("Test  :", X_test.shape)
# UNIVARIATE FEATURE SELECTION
kbest = SelectKBest( score_func=mutual_info_classif, k=min(20, X_train.shape[1]))
X_train_uni = kbest.fit_transform(X_train, y_train)
X_test_uni = kbest.transform(X_test)
selected_uni = X_train.columns[kbest.get_support()]
X_train_uni = pd.DataFrame( X_train_uni, columns=selected_uni )
X_test_uni = pd.DataFrame( X_test_uni, columns=selected_uni )
print("After Univariate :", X_train_uni.shape)
# RFE
base_model = LogisticRegression(max_iter=5000)
n_features = min(10, X_train_uni.shape[1])
rfe = RFE( estimator=base_model, n_features_to_select=n_features)
X_train_rfe = rfe.fit_transform(X_train_uni, y_train )
X_test_rfe = rfe.transform(X_test_uni)
final_features = X_train_uni.columns[rfe.support_]
X_train_rfe = pd.DataFrame( X_train_rfe, columns=final_features )
X_test_rfe = pd.DataFrame( X_test_rfe, columns=final_features )
print("Final Features")
print(final_features.tolist())
print("Train Shape :", X_train_rfe.shape)
print("Test Shape  :", X_test_rfe.shape)
# SMOTE
balancer = Balancing_Data( X_train_rfe, y_train )
X_smote_rs, y_smote_rs = balancer.SMOTE_with_RandomState(42)
print("SMOTE Shape :", X_smote_rs.shape)
# MODEL EVALUATION
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
models = {
    "Logistic Regression": LogisticRegression(max_iter=5000),
    "Gaussian NB": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier( random_state=42 ),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42)
}
results = []
for name, model in models.items():
    model.fit( X_smote_rs, y_smote_rs )
    y_pred = model.predict( X_test_rfe )
    acc = accuracy_score( y_test,y_pred)
    prec = precision_score( y_test, y_pred,zero_division=0)
    rec = recall_score(y_test,y_pred,zero_division=0)
    f1 = f1_score(y_test,y_pred,zero_division=0)
    print(name)
    print( "Accuracy :",round(acc,4))
    print( "Precision:",round(prec,4))
    print( "Recall   :",round(rec,4))
    print( "F1 Score :",round(f1,4))
    print( "Confusion Matrix\n",confusion_matrix(y_test,y_pred))
    results.append(
        [
            name,
            acc,
            prec,
            rec,
            f1
        ]
    )
# FINAL COMPARISON
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1"
    ]
)
# Recall primary, Accuracy secondary
results_df = results_df.sort_values(
    by=["Recall", "Accuracy"],
    ascending=[False, False]
)
print("\n")
print("BEST MODEL")
print(results_df)
best_model = results_df.iloc[0]["Model"]
best_recall = results_df.iloc[0]["Recall"]
best_accuracy = results_df.iloc[0]["Accuracy"]
print("FINAL SELECTED MODEL")
print("Model    :", best_model)
print("Recall   :", round(best_recall,4))
print("Accuracy :", round(best_accuracy,4))
print("Reason   : Highest Recall with Highest Accuracy")

"""# **WITH CROSS VALIDATION**"""

# CROSS VALIDATION
from sklearn.model_selection import cross_val_score
cv_results = {}
print("CROSS VALIDATION RESULTS")
cv_models = {
    "Logistic Regression": LogisticRegression(max_iter=5000),
    "Gaussian NB": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42)
}
for name, model in cv_models.items():
    cv_scores = cross_val_score(
        model,
        X_smote_rs,
        y_smote_rs,
        cv=5,
        scoring='recall'
    )
    cv_results[name] = round(cv_scores.mean(), 4)
    print(f"\n{name}")
    print("CV Scores :", cv_scores)
    print("Mean Recall :", round(cv_scores.mean(), 4))
    print("Std Dev :", round(cv_scores.std(), 4))
# FINAL COMPARISON
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1"
    ]
)
results_df["CV_Recall"] = results_df["Model"].map(cv_results)
results_df = results_df.sort_values(
    by=["Recall", "Accuracy", "CV_Recall"],
    ascending=[False, False, False]
)
print("\n================================")
print("MODEL COMPARISON")
print("================================")
print(results_df)
best_model = results_df.iloc[0]["Model"]
print("\n================================")
print("FINAL SELECTED MODEL")
print("================================")
print("Model      :", best_model)
print("Accuracy   :", round(results_df.iloc[0]["Accuracy"], 4))
print("Recall     :", round(results_df.iloc[0]["Recall"], 4))
print("CV Recall  :", round(results_df.iloc[0]["CV_Recall"], 4))
print("\nReason:")
print("Selected based on Highest Recall, Highest Accuracy and Highest Cross Validation Recall.")

"""# **Final Comparision**"""

# BEST MODEL WITHOUT CV
best_without_cv = results_df.sort_values( by=["Recall", "Accuracy"], ascending=[False, False] ).iloc[0]
# BEST MODEL WITH CV
best_with_cv = results_df.sort_values(
    by=["Recall", "Accuracy", "CV_Recall"],
    ascending=[False, False, False]
).iloc[0]
print("\n================================")
print("BEST MODEL WITHOUT CV")
print("================================")
print(best_without_cv["Model"])
print("\n================================")
print("BEST MODEL WITH CV")
print("================================")
print(best_with_cv["Model"])
# =====================================================
# FINAL WINNER
# =====================================================
if best_without_cv["Model"] == best_with_cv["Model"]:
    final_model = best_with_cv["Model"]
else:
    if best_with_cv["CV_Recall"] >= best_without_cv["CV_Recall"]:
        final_model = best_with_cv["Model"]
    else:
        final_model = best_without_cv["Model"]
print("\n================================")
print("FINAL BEST MODEL")
print("================================")
print("Model      :", final_model)
final_row = results_df[results_df["Model"] == final_model].iloc[0]
print("Accuracy   :", round(final_row["Accuracy"],4))
print("Recall     :", round(final_row["Recall"],4))
print("CV Recall  :", round(final_row["CV_Recall"],4))
print("\nReason : Selected using Recall, Accuracy and Cross Validation Recall.")

mi_scores = pd.DataFrame({
    "Feature": selected_uni,
    "Score": kbest.scores_[kbest.get_support()]
})
mi_scores = mi_scores.sort_values(
    by="Score",
    ascending=False
)
print(mi_scores)
plt.figure(figsize=(8,5))
sns.barplot(
    data=mi_scores,
    x="Score",
    y="Feature"
)
plt.title("Feature Relevance using Mutual Information")
plt.show()

top_features = mi_scores.head(10)
plt.figure(figsize=(8,5))
sns.barplot(
    data=top_features,
    x="Score",
    y="Feature"
)
plt.title("Top 10 Important Features")
plt.show()